version: '2'
services:
  # # this container generates a config to be used by teleport
  # configure:
  #   image: public.ecr.aws/gravitational/teleport-lab:10
  #   container_name: teleport-configure
  #   entrypoint: /bin/sh
  #   command: -c "/usr/bin/dumb-init teleport configure -o /etc/teleport/teleport.yaml ; sed -i -e '/nodename/d' /etc/teleport/teleport.yaml"
  #   volumes:
  #     - config:/etc/teleport

  # This container depends on the config written by the configure container above, so it
  # sleeps for a second on startup to allow the configure container to run first.
  teleport:
    image: public.ecr.aws/gravitational/teleport-lab:10
    container_name: teleport
    entrypoint: /bin/sh
    hostname: luna.teleport
    command: -c "/usr/bin/dumb-init teleport start -d -c /etc/teleport/teleport.yaml"
    ports:
      - "3023:3023"
      - "3024:3024"
      - "3025:3025"
      - "443:443"
    volumes:
      - $PWD/config/teleport-server.yaml:/etc/teleport/teleport.yaml
      - data:/var/lib/teleport
      - certs:/mnt/shared/certs
    # depends_on:
    #   - configure
    healthcheck:
      test: tctl status
      interval: 2s
      timeout: 2s
      retries: 3
      start_period: 5s
    networks:
      teleport:
        aliases:
          - proxy.luna.teleport

  # The bootstrap container generates certificates and then immediately exits.
  bootstrap:
    image: public.ecr.aws/gravitational/teleport-lab:10
    container_name: teleport-bootstrap
    entrypoint: /bin/sh
    command: -c "/etc/teleport.d/scripts/generate-certs.sh"
    volumes:
      # - config:/etc/teleport
      - data:/var/lib/teleport
      - certs:/mnt/shared/certs
    depends_on:
      - teleport
    networks:
      - teleport

  #
  # node1
  #
  node1:
    image: public.ecr.aws/gravitational/teleport-lab:10
    # entrypoint: /bin/sh
    # command: -c "/usr/bin/dumb-init teleport start -d -c /etc/teleport/teleport.yaml"
    volumes:
      - $PWD/config/teleport-client.yaml:/etc/teleport/teleport.yaml
      - certs:/mnt/shared/certs
    depends_on:
      teleport:
        condition: service_healthy
    networks:
      - teleport

  #
  # node2
  #
  node2:
    image: public.ecr.aws/gravitational/teleport-lab:10
    # entrypoint: /bin/sh
    # command: -c "/usr/bin/dumb-init teleport start -d -c /etc/teleport/teleport.yaml"
    volumes:
      - $PWD/config/teleport-client.yaml:/etc/teleport/teleport.yaml
      - certs:/mnt/shared/certs
    depends_on:
      teleport:
        condition: service_healthy
    networks:
      - teleport

  #
  # openssh is a demo of openssh node
  #
  openssh:
    image: public.ecr.aws/gravitational/teleport-lab:10
    container_name: openssh
    hostname: mars.openssh.teleport
    entrypoint: /bin/sh
    command: -c "/etc/teleport.d/scripts/start-sshd.sh"
    mem_limit: 300m
    volumes:
      - certs:/mnt/shared/certs
    depends_on:
      - bootstrap
    networks:
      teleport:
        aliases:
          - mars.openssh.teleport

  #
  # term is a container with a terminal to try things out
  #
  term:
    image: public.ecr.aws/gravitational/teleport-lab:10
    hostname: term
    container_name: term
    entrypoint: /bin/sh
    command: -c "sleep infinity"
    mem_limit: 300m
    volumes:
      - certs:/mnt/shared/certs
    depends_on:
      - bootstrap
    networks:
      - teleport

volumes:
  certs: 
  data: 
  # config: 

networks:
  teleport:

